Repository Tech-TTGames/Tickets-Plus, pull requests merged in 2023-03, with the labels that each got.

#31 Adding Clarification to README
  README.md
Labels: documentation

#34 The Update Update
  example_config.json
  extchecks.py
  main_utils.py
  override.py
  settings.py
  start_bot.py
  variables.py
Labels: enhancement, Feature

#35 Updating Workflows
  .github/workflows/dependency-review.yml
  .github/workflows/pylint.yml
Labels: workflow

#37 Formatting
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  SUPPORT.md
Labels: documentation

#36 Add documentation regarding thread creation logic
  main_utils.py
Labels: documentation

#39 Minor Message Discovery Update
  main_utils.py
  variables.py
Labels: enhancement

#41 Update Issue templates
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: documentation

#43 Issue forms, pull request template.
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/issue.yaml
  .github/ISSUE_TEMPLATE/question.yaml
  .github/pull_request_template.md
Labels: Type: Documentation, Priority: 3, Status: Ready

#44 [Formatting] Remove blank spaces
  .github/ISSUE_TEMPLATE/config.yml
Labels: Priority: 3, Type: Style

#48 Push more info from README to pages.
  README.md
Labels: Type: Style

#18 Major Rewrite
  .deepsource.toml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/pylint.yml
  .gitignore
  README.md
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  branding/LICENSE
  branding/android-chrome-192x192.png
  branding/android-chrome-512x512.png
  branding/apple-touch-icon.png
  branding/browserconfig.xml
  branding/favicon-16x16.png
  branding/favicon-32x32.png
  branding/favicon.ico
  branding/logo.jpg
  branding/mstile-150x150.png
  branding/rounded.png
  branding/safari-pinned-tab.svg
  branding/site.webmanifest
  docs/database_info.html
  example_alembic.ini
  example_config.json
  extchecks.py
  main_utils.py
  override.py
  pdoc/module.html.jinja2
  pdoc/syntax-highlighting.css
  pdoc/theme.css
  poetry.lock
  pylintrc
  pyproject.toml
  requirements.txt
  settings.py
  start_bot.py
  tickets_plus/__init__.py
  tickets_plus/__main__.py
  tickets_plus/bot.py
  tickets_plus/cogs/__init__.py
  tickets_plus/cogs/errors.py
  tickets_plus/cogs/events.py
  tickets_plus/cogs/main_utils.py
  tickets_plus/cogs/override.py
  tickets_plus/cogs/settings.py
  tickets_plus/database/__init__.py
  tickets_plus/database/layer.py
  tickets_plus/database/models.py
  tickets_plus/database/statvars.py
  tickets_plus/ext/__init__.py
  tickets_plus/ext/checks.py
  tickets_plus/ext/exceptions.py
  tickets_plus/ext/views.py
  toolbox/migrate.py
  toolbox/nuke.py
  variables.py
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Priority: 2, Status: Ready, Archive: Old Style, Type: Style

#61 Ban Commands and Descriptor Data
  alembic/env.py
  alembic/versions/ae5d2cc3d90b_v0_1_0_1_database.py
  example_alembic.ini
  tickets_plus/cogs/errors.py
  tickets_plus/cogs/events.py
  tickets_plus/cogs/main_utils.py
  tickets_plus/cogs/routines.py
  tickets_plus/cogs/settings.py
  tickets_plus/cogs/staff.py
  tickets_plus/database/layer.py
  tickets_plus/database/models.py
  tickets_plus/database/statvars.py
Labels: Type: Enhancement, Type: Feature, Priority: 3, Status: Ready
